import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";

export const metadata = {
  title: "BreachIQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-white min-h-screen flex flex-col">
      <Header />
      {children}
      <Footer/>
    </div>
  );
}
