export const metadata = {
  title: "BreachIQ - Login",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return <div className="bg-white">{children}</div>;
}
