import "./globals.css";
import { Host_Grotesk } from "next/font/google";

export const metadata = {
  title: "BreachIQ",
  description: "Generated by create next app",
};

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${hostGrotesk.className} antialiased bg-white`}>
        {children}
      </body>
    </html>
  );
}
